### ISSUE TITLE
Question about labels?

### ISSUE THREAD

**Issue by FarnooshGhadiri** [Tai-Hsien/Mesh_Labeler#1]
Hi, Thank you for the amazing software that you are provided, is it possible for you to add a description about labels such as B L, AK..the labels in the second row?

**Comment by Tai-Hsien** [comment]
Hello,
Thanks for your suggestion. I might find a time to refine the colormap and add description.
In case you have no idea, the labels such as B L, A K, etc. are the primary teeth, which I borrow from https://dentalimplants-usa.com/bone-and-teeth/tooth-numbering/
