### ISSUE TITLE
label overlay is not working

### ISSUE THREAD

**Issue by qianyizhang** [Tai-Hsien/Mesh_Labeler#2]
great tool!
However, the overlay is not displayed properly in my case. Eg. no color change after spline execusion (but i can still save them correctly).
Furthermore, the loaded labeled data also not displayed properly, below is the display of Eample1.vtk
Any idea why?
![image](https://user-images.githubusercontent.com/12500132/119596554-fc353900-be11-11eb-9268-2a63f9172901.png)

**Comment by Tai-Hsien** [comment]
Hello,
Is this the included example file? It looks so weird. I have seen any sample like this.
Do you use portable version? If so, would you like to try to install it using installer (the one I just released today).

**Comment by qianyizhang** [comment]
quick response!
i think it has to do with the memory misalignment, did you compile the protable with 32 bit? i will give it a try of the installer.

**Comment by Tai-Hsien** [comment]
It's not 32-bit. My developing machine is 64-bit. Please let me know the result of installer. Many thanks!

**Comment by qianyizhang** [comment]
fyi, i also found this livewire3d repo while researching on tooth labeling tool, it think it's a great complement to your tool
https://github.com/yixin26/LiveWire3D

**Comment by Tai-Hsien** [comment]
Interesting work! I will take a look!

**Comment by qianyizhang** [comment]
unfortunately, the problem still exists. landmark labelling works though (in both portable and installer version)
or maybe it has to do with driver? i am using laptop without dedicated graphic card

**Comment by Tai-Hsien** [comment]
Hello,
I will guess the problem is from graphic card. What's the card you used?

**Comment by qianyizhang** [comment]
like i said, i am using a laptop (Intel CPU) without dedicated graphic card

vedo example works fine on my laptop
can you give me the minimum reproduction code to visualize your label overlay?
![image](https://user-images.githubusercontent.com/12500132/119756951-d0c85200-bed6-11eb-9f16-ecfb787f0a6c.png)

**Comment by Tai-Hsien** [comment]
Hello,
Please try
```
from vedo import *

if __name__ == '__main__':

    mesh = load('Example_01.vtp')
    vp = Plotter()
    vp.add(mesh)
    vp.show()
```

**Comment by Tai-Hsien** [comment]
BTW, I also tested the program on my Intel laptop with Intel HD Graphics 520. Everything just works fine. Maybe reinstall/upgrade the driver of graphic card?

**Comment by qianyizhang** [comment]
vedo display is also wrong T.T
strangely, the wireframe display is correct, only the surface display is wrong...
i am asking help on the vedo repo, thanks

**Comment by Tai-Hsien** [comment]
Hello @qianyizhang 
My understanding is that vedo is based on VTK, so maybe you can also reach out to Kitware (the company who maintain VTK).
