### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by hfpro** [Tai-Hsien/Mesh_Labeler#4]
it would be nice to post information on hotkeys

**Comment by Tai-Hsien** [comment]
It's a good suggestion. I will work on it! Thanks for the feedback!

**Comment by hfpro** [comment]
thank you, we will be waiting

**Comment by Tai-Hsien** [comment]
Hello,

I have updated the README file to include a brief hotkey table.

Best,

**Comment by hfpro** [comment]
Thank you very much
