### ISSUE TITLE
download installer

### ISSUE THREAD

**Issue by tomanick** [Tai-Hsien/Mesh_Labeler#6]
It looks like a very good software.
However, when I wanted to download the mesh_labeler installer, it could not be downloaded from the website which you provided.
Can you share it again or send it to me in email?
Thank you very much.

**Comment by Tai-Hsien** [comment]
Thanks for pointing out this problem. Recently, I changed the cloud server for this installer. I will update the new link soon!

**Comment by Tai-Hsien** [comment]
> It looks like a very good software. However, when I wanted to download the mesh_labeler installer, it could not be downloaded from the website which you provided. Can you share it again or send it to me in email? Thank you very much.

updated! Feel free to let me know if you still have problems to download.

**Comment by Si7uu** [comment]
Hello! 
I'm sorry to bother you that the mesh_labeler installer still could not be downloaded from the website which you provided.

> > It looks like a very good software. However, when I wanted to download the mesh_labeler installer, it could not be downloaded from the website which you provided. Can you share it again or send it to me in email? Thank you very much.
> 
> updated! Feel free to let me know if you still have problems to download.

**Comment by Tai-Hsien** [comment]
Have you seen the following page? If so, click the download on the top left.
![image](https://user-images.githubusercontent.com/9615481/163512095-d91a6de8-6aa9-4e27-9b7b-394bad637864.png)

**Comment by Si7uu** [comment]
I don't know if it's somthing wrong with my network. Actually, I have changed several computers, but still could not open this web page which you provided. 
![微信图片_20220415111918](https://user-images.githubusercontent.com/103714947/163512905-7f0b409e-2e95-4dee-834b-a33d7418c1da.png)

**Comment by Si7uu** [comment]
I don't know if it's somthing wrong with my network. Actually, I have changed several computers, but still could not open this web page which you provided.
![微信图片_20220415111918](https://user-images.githubusercontent.com/103714947/163512994-85e1703b-8cd9-4bb4-b467-7deb27c9f0fa.png)

**Comment by Tai-Hsien** [comment]
The only reason I can guess is dropbox is not accessible in China, which I cannot help.

**Comment by Si7uu** [comment]
Oh no! It makes me so sad! I have an presumptuous request that, I wonder if it is convenient for u to download the software and send it to my email address. I really want to use your program to label my dental mesh model! 
My email address is Si7uxiuwen@outlook.com

**Comment by Tai-Hsien** [comment]
It's approximately 115 MB which is too big as an attachment in email.

**Comment by Si7uu** [comment]
Well, thank you for all your help. Have a good life!

**Comment by Tai-Hsien** [comment]
One possible solution is to use VPN; however, I don't know it's legal or not in China. Good luck on your research!
