### ISSUE TITLE
View vtp file

### ISSUE THREAD

**Issue by archetype-2** [Tai-Hsien/Mesh_Labeler#7]
Hi there,

Not sure why when i try to view a vtp file on this application, it appears like this. The labels are clearly there however. Is there something I can do?
Thanks a lot for the help!

![meshlabelerror](https://user-images.githubusercontent.com/110601496/182820018-4b18c938-fa44-4bae-901a-a5fa8364f3ff.png)

**Comment by Tai-Hsien** [comment]
What is the problem with that view? It looks normal to me. Did you try to zoom in to look at it?
