### ISSUE TITLE
will you share the  datasets of  meshsegnet?

### ISSUE THREAD

**Issue by zhongxiaj** [Tai-Hsien/Mesh_Labeler#8]
great work ! will you share the  datasets of  meshsegnet?   I really need them , thanks

**Comment by Tai-Hsien** [comment]
Hello,

Sorry that we are not able to share the dataset due to patients' privacy.

**Comment by Tai-Hsien** [comment]
If you need the dataset for inrtraoral scans, you might check https://3dteethseg.grand-challenge.org/

**Comment by zhongxiaj** [comment]
> If you need the dataset for inrtraoral scans, you might check https://3dteethseg.grand-challenge.org/

Thanks for your reply! I have some labeled  mesh scans  but  they are .stl. How can I send them to  the meshSegNet? Is there any guide line for me to  organize custom datasets for instance seg? I am a St. and a green hand about  instance seg. Thanks

**Comment by Tai-Hsien** [comment]
MeshSegNet is actually semantic segmentation instead of instance segmentation. Our samples are in VTK format. You can use vedo (https://vedo.embl.es/) to convert STL to VTK; focus on pointdata and/or celldata to learn how to use point/cell array to store the label, which is the code behind "Mesh Labeler".

**Comment by zhongxiaj** [comment]
> MeshSegNet is actually semantic segmentation instead of instance segmentation. Our samples are in VTK format. You can use vedo (https://vedo.embl.es/) to convert STL to VTK; focus on pointdata and/or celldata to learn how to use point/cell array to store the label, which is the code behind "Mesh Labeler".

got it, thanks very much!
